name: Trigger auto deployment for containerapp weathertest4

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/weathertest4-AutoDeployTrigger-7c5f9249-0da2-4769-a9ab-bb834c42cfcd.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca9fe846c7e1acr.azurecr.io
          username: ${{ secrets.WEATHERTEST4_REGISTRY_USERNAME }}
          password: ${{ secrets.WEATHERTEST4_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca9fe846c7e1acr.azurecr.io/weathertest4:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WEATHERTEST4_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n weathertest4 -g timheuer_rg_3991 --server ca9fe846c7e1acr.azurecr.io --username  ${{ secrets.WEATHERTEST4_REGISTRY_USERNAME }} --password ${{ secrets.WEATHERTEST4_REGISTRY_PASSWORD }}
            az containerapp update -n weathertest4 -g timheuer_rg_3991 --image ca9fe846c7e1acr.azurecr.io/weathertest4:${{ github.sha }}
